export {default as Discover} from './Discover'
export {default as List} from './List' 
export {default as MyList} from './MyList'
export {default as Sidebar} from './Sidebar'
export {default as Slider} from './Slider'